WRITE [(Sophia,Andresen)(Jorge,Luis)]
WRITE [(Miguel,Cervantes)(Pablo,Neruda)]
WRITE [(Gabriel,Marquez)(Clarice,Lispector)]
WRITE [(José,Saramago)(Virginia,Woolf)]
WRITE [(Leo,Tolstoy)(Franz,Kafka)]
WRITE [(Oscar,Wilde)(Emily,Dickinson)]
WRITE [(Edgar,Allan)(Charles,Dickens)]
WRITE [(Mark,Twain)(Herman,Melville)]
WRITE [(Haruki,Murakami)(Italo,Calvino)]
WRITE [(Marcel,Proust)(Jane,Austen)]
WRITE [(Agatha,Christie)(J.K.,Rowling)]
WRITE [(Stephen,King)(George,Orwell)]
WRITE [(Aldous,Huxley)(J.R.R.,Tolkien)]
WRITE [(C.S.,Lewis)(William,Faulkner)]
WRITE [(James,Joyce)(Ernest,Hemingway)]
WRITE [(Toni,Morrison)(Chinua,Achebe)]
WRITE [(Isabel,Allende)(Zadie,Smith)]
WRITE [(Fyodor,Dostoevsky)(Victor,Hugo)]
WRITE [(Albert,Camus)(Simone,Oliveira)]
SHOW
SHOW
SHOW
SHOW
SHOW
BACKUP

