WRITE [(Liam,Nelson)(Emma,Stone)]
WRITE [(Chris,Hemsworth)(Scarlett,Johansson)]
WRITE [(Robert,Downey)(Natalie,Portman)]
WRITE [(Leonardo,DiCaprio)(Kate,Winslet)]
WRITE [(Denzel,Washington)(Meryl,Streep)]
WRITE [(Tom,Hanks)(Julia,Roberts)]
WRITE [(Will,Smith)(Margot,Robbie)]
SHOW
SHOW
WRITE [(Christian,Bale)(Amy,Adams)]
WRITE [(Brad,Pitt)(Angelina,Jolie)]
WRITE [(Johnny,Depp)(Helena,Bonham)]
WRITE [(Morgan,Freeman)(Anne,Hathaway)]
SHOW
WRITE [(Matt,Damon)(Sandra,Bullock)]
WRITE [(Joaquin,Phoenix)(Reese,Witherspoon)]
WRITE [(Daniel,Radcliffe)(Emma,Watson)]
WRITE [(Hugh,Jackman)(Nicole,Kidman)]
WRITE [(Ryan,Gosling)(Rachel,McAdams)]
SHOW
WRITE [(Keanu,Reeves)(Carrie,Moss)]
WRITE [(Chadwick,Boseman)(Lupita,Nyong)]
WRITE [(Ben,Affleck)(Gal,Gadot)]
WRITE [(Jason,Momoa)(Amber,Heard)]

SHOW
SHOW
SHOW
