WRITE [(Gustavo,Lima)(Carlos,Vinícius)]
WRITE [(Nicolas,Mendes)(Alberto,Pereira)]
WRITE [(Fabiana,Alves)(Adriana,Lopes)]
WRITE [(Cristina,Sousa)(Alexandre,Rodrigues)]
WRITE [(Paulo,Carvalho)(Renata,Teixeira)]
SHOW
SHOW
SHOW
SHOW
WRITE [(Helena,Monteiro)(Marco,Ferreira)]
WRITE [(Fernando,Gomes)(Patrícia,Barros)]
WRITE [(Rafael,Martins)(Camila,Ribeiro)]
WRITE [(Eduarda,Silva)(Sérgio,Oliveira)]
WRITE [(Amanda,Santos)(Hugo,Pires)]
WRITE [(Luciana,Nogueira)(Ricardo,Mendes)]
SHOW
SHOW
SHOW
SHOW
WRITE [(Jéssica,Costa)(Rogério,Lima)]
WRITE [(Rodrigo,Pinto)(Larissa,Amorim)]
WRITE [(Tatiana,Vieira)(Diego,Marques)]
WRITE [(Gisele,Ferreira)(Juliano,Rocha)]
WRITE [(Douglas,Ramos)(Viviane,Lima)]
WRITE [(Anderson,Moura)(Kelly,Neves)]
WRITE [(Fábio,Castro)(Cláudia,Barbosa)]
WRITE [(Mariana,Matos)(Márcio,Coelho)]
WRITE [(Júnior,Bastos)(Carolina,Gomes)]
SHOW
